services:
  api:
    env_file:
      - .env
    build:
      context: ./api
      args:
        - DEV=false
    volumes:
      - ./api/ett_backend:/ett_backend
      - ./pyproject.toml:/ett_backend/pyproject.toml
      - ./mypy.ini:/ett_backend/mypy.ini
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - WERKZEUG_DEBUG_PIN=off
      - TZ="Asia/Seoul"
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 config.wsgi.application --workers 3 --log-level info"
