# Generated by Django 5.0.7 on 2024-07-11 06:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chat_room_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("analyze_target_name", models.CharField(max_length=255)),
                ("analyze_target_relation", models.CharField(max_length=255)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.user")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserDialog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.user")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AIDialog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.user")),
                (
                    "user_dialog",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="dialog.userdialog"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
