# Generated by Django 5.0.7 on 2024-07-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dialog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="aidialog",
            table="ai_dialog",
        ),
        migrations.AlterModelTable(
            name="userdialog",
            table="user_dialog",
        ),
    ]
