# Generated by Django 5.0.7 on 2024-07-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dialog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="char_room_name",
            field=models.CharField(default="채팅방", max_length=255),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="analyze_target_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="analyze_target_relation",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
