# Generated by Django 5.0.7 on 2024-07-12 05:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dialog", "0002_chatroom_char_room_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="char_room_name",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="chat_room_id",
        ),
        migrations.AddField(
            model_name="aidialog",
            name="chat_room",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="dialog.chatroom"),
        ),
        migrations.AddField(
            model_name="aidialog",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="chat_room_name",
            field=models.CharField(default="My Chat Room", max_length=255),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="chat_room_uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="userdialog",
            name="chat_room",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="dialog.chatroom"),
        ),
        migrations.AddField(
            model_name="userdialog",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
    ]
