# Generated by Django 5.0.7 on 2024-07-19 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0003_alter_chatroom_chat_room_uuid"),
        ("dialog", "0002_alter_aidialog_table_alter_userdialog_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aidialog",
            name="chat_room",
        ),
        migrations.RemoveField(
            model_name="aidialog",
            name="user",
        ),
        migrations.AlterField(
            model_name="userdialog",
            name="chat_room",
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to="chatroom.chatroom"),
        ),
    ]
