# Generated by Django 5.0.7 on 2024-07-16 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0001_initial"),
        ("dialog", "0003_remove_chatroom_char_room_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdialog",
            name="chat_room",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="chatroom.chatroom"),
        ),
        migrations.AlterField(
            model_name="aidialog",
            name="chat_room",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="chatroom.chatroom"),
        ),
        migrations.DeleteModel(
            name="ChatRoom",
        ),
    ]
