# Generated by Django 5.0.7 on 2024-07-23 00:47

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dialog", "0003_remove_aidialog_chat_room_remove_aidialog_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdialog",
            old_name="text",
            new_name="message",
        ),
        migrations.RemoveField(
            model_name="aidialog",
            name="text",
        ),
        migrations.AddField(
            model_name="aidialog",
            name="message",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="aidialog",
            name="message_uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name="aidialog",
            name="sentiments",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="userdialog",
            name="message_uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
