# Generated by Django 5.0.7 on 2024-07-23 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dialog", "0004_rename_text_userdialog_message_remove_aidialog_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aidialog",
            name="sentiments",
        ),
        migrations.AddField(
            model_name="aidialog",
            name="applied_state",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="AIEmotionalAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("happiness", models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ("anger", models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ("sadness", models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ("worry", models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ("indifference", models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ("ai_dialog", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="dialog.aidialog")),
            ],
            options={
                "db_table": "ai_emotional_analysis",
            },
        ),
    ]
