# Generated by Django 5.0.7 on 2024-07-24 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0005_remove_chatroom_analyze_target_name"),
        ("dialog", "0005_remove_aidialog_sentiments_aidialog_applied_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdialog",
            name="chat_room",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_dialog",
                to="chatroom.chatroom",
            ),
        ),
    ]
