# Generated by Django 5.0.7 on 2024-07-24 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dialog", "0006_alter_userdialog_chat_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aidialog",
            name="user_dialog",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="ai_dialog", to="dialog.userdialog"
            ),
        ),
    ]
