# Generated by Django 5.0.7 on 2024-07-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dialog", "0008_alter_userdialog_chat_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiemotionalanalysis",
            name="anger",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="aiemotionalanalysis",
            name="happiness",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="aiemotionalanalysis",
            name="indifference",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="aiemotionalanalysis",
            name="sadness",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="aiemotionalanalysis",
            name="worry",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
