# Generated by Django 5.0.7 on 2024-07-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="chatroom",
            table="chat_room",
        ),
    ]
