# Generated by Django 5.0.7 on 2024-07-23 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0003_alter_chatroom_chat_room_uuid"),
        ("trees", "0007_alter_treedetail_forest_alter_treedetail_tree_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="analyze_target_relation",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="tree",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="trees.treedetail"),
        ),
    ]
