# Generated by Django 5.0.7 on 2024-07-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0004_remove_chatroom_analyze_target_relation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="analyze_target_name",
        ),
    ]
