# Generated by Django 5.0.7 on 2024-07-17 12:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("username", models.CharField(max_length=255, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("profile_image", models.URLField(max_length=255, null=True)),
                (
                    "social_platform",
                    models.CharField(
                        choices=[("none", "none"), ("kakao", "kakao"), ("google", "google")],
                        default="none",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
