# Generated by Django 5.0.7 on 2024-07-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_is_active_user_is_staff_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
    ]
