# Generated by Django 5.0.7 on 2024-07-11 06:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreeMap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tree_map_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("tree_level", models.PositiveIntegerField(default=0)),
                ("happiness", models.PositiveIntegerField(default=0)),
                ("anger", models.PositiveIntegerField(default=0)),
                ("sadness", models.PositiveIntegerField(default=0)),
                ("pleasure", models.PositiveIntegerField(default=0)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="users.user")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TreeDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tree_name", models.CharField(default="", max_length=255)),
                ("tree_growth_level", models.PositiveIntegerField(default=0)),
                ("location_x", models.IntegerField(default=0)),
                ("location_y", models.IntegerField(default=0)),
                ("tree_map", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="trees.treemap")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
