# Generated by Django 5.0.7 on 2024-07-17 12:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TreeMap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("tree_map_uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("tree_level", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TreeDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("tree_name", models.CharField(default="My Tree", max_length=255)),
                ("tree_growth_level", models.PositiveIntegerField(default=0)),
                ("location_x", models.IntegerField(default=0)),
                ("location_y", models.IntegerField(default=0)),
                ("happiness", models.DecimalField(decimal_places=1, max_digits=2)),
                ("anger", models.DecimalField(decimal_places=1, max_digits=2)),
                ("sadness", models.DecimalField(decimal_places=1, max_digits=2)),
                ("worry", models.DecimalField(decimal_places=1, max_digits=2)),
                ("indifference", models.DecimalField(decimal_places=1, max_digits=2)),
                ("tree_map", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="trees.treemap")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
