# Generated by Django 5.0.7 on 2024-07-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="treemap",
            name="anger",
        ),
        migrations.RemoveField(
            model_name="treemap",
            name="happiness",
        ),
        migrations.RemoveField(
            model_name="treemap",
            name="pleasure",
        ),
        migrations.RemoveField(
            model_name="treemap",
            name="sadness",
        ),
        migrations.AddField(
            model_name="treedetail",
            name="anger",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="treedetail",
            name="happiness",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="treedetail",
            name="indifference",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="treedetail",
            name="pleasure",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="treedetail",
            name="sadness",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
