# Generated by Django 5.0.7 on 2024-07-18 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forest", "0002_remove_forest_trees_forest_tree_level_and_more"),
        ("trees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treedetail",
            name="tree_map",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="forest.forest"),
        ),
        migrations.DeleteModel(
            name="TreeMap",
        ),
    ]
