# Generated by Django 5.0.7 on 2024-07-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0002_remove_treemap_anger_remove_treemap_happiness_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="treemap",
            old_name="tree_map_id",
            new_name="tree_map_uuid",
        ),
        migrations.RemoveField(
            model_name="treedetail",
            name="indifference",
        ),
        migrations.AddField(
            model_name="treedetail",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="treemap",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="treedetail",
            name="tree_name",
            field=models.CharField(default="My Tree", max_length=255),
        ),
    ]
