# Generated by Django 5.0.7 on 2024-07-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0002_alter_treedetail_tree_map_delete_treemap"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="treedetail",
            table="tree_detail",
        ),
    ]
