# Generated by Django 5.0.7 on 2024-07-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0003_rename_tree_map_id_treemap_tree_map_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="treedetail",
            name="indifference",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
