# Generated by Django 5.0.7 on 2024-07-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0004_rename_tree_map_treedetail_forest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treedetail",
            name="tree_name",
            field=models.CharField(default="My Tree", max_length=255),
        ),
    ]
