# Generated by Django 5.0.7 on 2024-07-15 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0004_treedetail_indifference"),
    ]

    operations = [
        migrations.RenameField(
            model_name="treedetail",
            old_name="pleasure",
            new_name="worry",
        ),
    ]
