# Generated by Django 5.0.7 on 2024-07-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0005_rename_pleasure_treedetail_worry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treedetail",
            name="anger",
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name="treedetail",
            name="happiness",
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name="treedetail",
            name="indifference",
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name="treedetail",
            name="sadness",
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name="treedetail",
            name="worry",
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
