# Generated by Django 5.0.7 on 2024-07-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0005_alter_treedetail_tree_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treeemotion",
            name="anger",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="treeemotion",
            name="happiness",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="treeemotion",
            name="indifference",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="treeemotion",
            name="sadness",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="treeemotion",
            name="worry",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
