# Generated by Django 5.0.7 on 2024-07-22 04:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forest", "0004_rename_tree_level_forest_forest_level_and_more"),
        ("trees", "0006_alter_treeemotion_anger_alter_treeemotion_happiness_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treedetail",
            name="forest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="related_tree", to="forest.forest"
            ),
        ),
        migrations.AlterField(
            model_name="treedetail",
            name="tree_uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
