# Generated by Django 5.0.7 on 2024-07-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forest", "0002_remove_forest_trees_forest_tree_level_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="forest",
            table="forest",
        ),
    ]
